[build]
  functions = "functions"
  publish = "public"
  command = ""

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
